MaxFeaturesPerTile = 150000

# Cache for 24 hours. 0 means no cachke control header wiil be set
CacheTTL = 86400

CORSOrigins = ["*"]

UrlBase = "http://20.56.94.119/pg4w/tileserv/"

BasePath = "/pg4w/tileserv/"